### ISSUE TITLE
Porting checklist

### ISSUE THREAD

**Issue by japareaggae** [japareaggae/certainmangareader#1]
Most of these features should be working before submitting a pull request back to Saishy.

## Manga list (panel)
- [ ] Latest chapter
- [ ] All chapters
- [ ] Start reading
- [ ] Mark as read
- [ ] Remove
- [ ] Last updated
- [ ] Source

## Manga toolbar (on the website)
- [ ] Add to list
- [ ] Go to main page
- [ ] Chapter selection
- [ ] Mark as read
- [ ] Side by side view

## Settings
- [ ] Toggle notifications
- [ ] Compact design
- [ ] Page numbers
- [ ] Infinite scrolling
- [ ] Update timer
- [ ] Import/export
- [ ] Manual updating

## Website support
- [ ] Batoto
- [ ] Mangafox
- [ ] Mangastream
- [ ] ReadMangaToday
- [ ] MangaHere
- [ ] MangaReader
